### ISSUE TITLE
Crash when hitting rate-limit

### ISSUE THREAD

**Issue by Brawl345** [Brawl345/RSSBot-Sharp#4]
The bot crashes when it receives more than ~20 messages and has to send them all at once. This is because it is hitting [Telegram's rate limit](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this):

* Avoid sending more than one message per second
* The API will not allow more than 30 messages per second or so
* Also note that your bot will not be able to send more than 20 messages per minute to the same group

Message:
```
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at RSSBot.Commands.Sync()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

The 429 error must be handled and syncing has to be postponed until all messages are sent - ideally not more than 20 per minute. Also doubled messages have to be avoided.

**Comment by Akamaru** [comment]
It would be great if it only sent the last 20 messages to avoid spam
